---
- hosts: all
  gather_facts: no
  collections:
    - ansible.netcommon
  tasks:
    - name: Add a server
      delegate_to: localhost
      community.network.netscaler_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        operation: add
        resource: server
        name: test-server-1
        attributes:
          name: test-server-1
          ipaddress: 192.168.1.1
