---
- hosts: all
  gather_facts: no
  collections:
  - junipernetworks.junos
  - ansible.netcommon
  tasks:
    - name: Darag BLACKLIST
      junipernetworks.junos.junos_config:
        src: tosend
        comment: New IP added to BLACKLIST
